### ISSUE TITLE
Navigation Order

### ISSUE THREAD

**Issue by armoucar-neon** [alfredbirk/go-to-next-change#5]
Props for you for putting up this new extension, it rocks.

Small issue: With a list of changes, vscode displays it in a order, but the navigates through those files in a different order.

![go-to-next-change](https://github.com/alfredbirk/go-to-next-change/assets/141850116/058cda0b-4801-42b1-8eb5-eb475741887e)

**Comment by alfredbirk** [comment]
Thanks! 

✅ This should now be fixed in v0.5.2, let me know if it works.

One issue I had is that List and Tree view have different orderings. I have made function to order correctly for both list view and tree view, but I don't know any way to automatically detect whether the user has List or Tree view activated.

So I made a new setting for the extension to solve it. If you use tree view, find the setting called `Go to next change: Tree view` and check off the box. 

I will let the issue stay open in case anyone who comes in knows a way to auto-detect it.
